### ISSUE TITLE
Update htmlproofer

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/jacobtomlinson.github.io#50]
The cli for the testing application [html-proofer](https://github.com/gjtorikian/html-proofer) was renamed from `htmlproof` to `htmlproofer` in gjtorikian/html-proofer#246.

The `Gemfile` needs updating to `> 3.x` and the `Rakefile` needs updating with the new command.

Picked up thanks to #49.

**Comment by outloudvi** [comment]
Continue it since not closed :)
There is something new:

```
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
```

Disappeared after removing `html-proofer`.

Ref: 
* https://travis-ci.org/outloudvi/pages/builds/162525155
* https://travis-ci.org/outloudvi/pages/builds/162527079
